In [2]:
#Data From https://simplemaps.com/city/nashville/zips/income-household-median

import pandas as pd
data = {
    'Zip code': ['37013', '37027', '37072', '37076', '37080', '37115', '37138', '37143', '37189', '37201',
                 '37203', '37204', '37205', '37206', '37207', '37208', '37209', '37210', '37211', '37212',
                 '37214', '37215', '37216', '37217', '37218', '37219', '37220', '37221', '37228'],
    'Average Income': [59015, 139932, 63784, 65870, 56763, 46123, 72861, 69934, 75690, 76014, 57330, 87292, 106241,
                       59203, 42973, 39964, 54461, 36283, 56748, 63586, 61558, 127203, 61641, 49103, 46974, 87344,
                       119803, 83331, 31451]
}

income_df = pd.DataFrame(data)
income_df

   Zip code  Average Income
0     37013           59015
1     37027          139932
2     37072           63784
3     37076           65870
4     37080           56763
5     37115           46123
6     37138           72861
7     37143           69934
8     37189           75690
9     37201           76014
10    37203           57330
11    37204           87292
12    37205          106241
13    37206           59203
14    37207           42973
15    37208           39964
16    37209           54461
17    37210           36283
18    37211           56748
19    37212           63586
20    37214           61558
21    37215          127203
22    37216           61641
23    37217           49103
24    37218           46974
25    37219           87344
26    37220          119803
27    37221           83331
28    37228           31451

In [3]:
folder_path = '../data/'
income_df.to_csv(folder_path + 'income.csv', index=False)

OSError: Cannot save file into a non-existent directory: '..\data'